spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${username}
    password: ${password}
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: false
    open-in-view: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs

api_key: ${weatherApiKey}
api_url: https://api.weatherapi.com/v1

resilience4j:
  ratelimiter:
    instances:
      weatherAPI:
        limit-for-period: 1
        limit-refresh-period: 10000s
        timeout-duration: 10000s
